In [113]:
import pandas as pd
import numpy as np

QUITAR EL # si no e tiene openpyxl

In [114]:

#!pip install openpyxl

In [115]:
df = pd.read_excel("TSP LatitudYLongitud.xlsx")

In [116]:
df

,colonia,Calle,# de casa,Código postal,Unnamed: 4,Ubicacion,Latitude,Longitude
0,U H FOVISSSTE ESTADI,LISBOA,28,44307,Guadalajara,U H FOVISSSTE ESTADI LISBOA 28 44307 Guadalajara,20.710556,-103.324800
1,INDEPENDENCIA,ROGELIO BACON,2280,44290,Guadalajara,INDEPENDENCIA ROGELIO BACON 2280 44290 Guadala...,20.711324,-103.332088
2,BOSQUES D LA CANTERA,PRIV OPALO,17,44306,Guadalajara,BOSQUES D LA CANTERA PRIV OPALO 17 44306 Guada...,20.715729,-103.314695
3,JARDINES DE LOS POET,JOSE FERNANDEZ,3365,44820,Guadalajara,JARDINES DE LOS POET JOSE FERNANDEZ 3365 44820...,20.648861,-103.293037
4,LOMAS DEL GALLO,FERNANDO SOLIS,1338,44760,Guadalajara,LOMAS DEL GALLO FERNANDO SOLIS 1338 44760 Guad...,20.679106,-103.270528
...,...,...,...,...,...,...,...,...
284,MESA COLORADA PTE,DELLI,1825,45189,zapopan,MESA COLORADA PTE DELLI 1825 45189 zapopan,20.770500,-103.347956
285,VILLA FONTANA DIAMANTE,AV LAS TORRES,1896,45200,zapopan,VILLA FONTANA DIAMANTE AV LAS TORRES 1896 4520...,20.774408,-103.475693
286,REAL DE TESISTAN,PASEO DE LA ARB,176,45200,zapopan,REAL DE TESISTAN PASEO DE LA ARB 176 45200 zap...,20.782630,-103.472207
287,EL CENTINELA 2,HIDALGO,310,45187,zapopan,EL CENTINELA 2 HIDALGO 310 45187 zapopan,20.758818,-103.379668
288,LA VENTA DEL ASTILLE,JILGEROS,33,45221,zapopan,LA VENTA DEL ASTILLE JILGEROS 33 45221 zapopan,20.725640,-103.546219

PON EL NÚMERO DE NODOS QUE NECESITES

In [117]:
no_nodes = 200

In [118]:
import math

def measure(lat1, lon1, lat2, lon2):
    # Radius of Earth in kilometers
    R = 6378.137

    dLat = math.radians(lat2 - lat1)
    dLon = math.radians(lon2 - lon1)
    # print(lat1, lat2)
    # print(lon1, lon2)
    # print(dLat, dLon)

    a = math.sin(dLat / 2) * math.sin(dLat / 2) + math.cos(math.radians(lat1)) * math.cos(math.radians(lat2)) * math.sin(dLon / 2) * math.sin(dLon / 2)
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))
    d = R * c
    return d #kilometers

In [119]:
range_depot = list(range(1, no_nodes + 1))

In [120]:
#Create 10 samples of 40 nodes and the distance matrix
for i in range(10):
    sample = df.sample(no_nodes)
    sample = sample.reset_index(drop=True)
    sample.to_csv("sample" + str(i) + ".csv", index=False)
    
    # Create the dist matrix in a dataframe
    
    
    dist_matrix = np.zeros((no_nodes, no_nodes))
    for w in range(no_nodes):
        for j in range(no_nodes):
            # print(w, j)            
            dist_matrix[w][j] = round(measure(sample.iloc[w]["Latitude"], sample.iloc[w]["Longitude"], sample.iloc[j]["Latitude"], sample.iloc[j]["Longitude"]), 2)

    # Change the diagonal to 999
    np.fill_diagonal(dist_matrix, 999)
    pd_dist_matrix = pd.DataFrame(dist_matrix, columns=range_depot, index=range_depot)
    pd_dist_matrix[pd_dist_matrix == 0] = 0.01
    
    pd_dist_matrix.to_csv("dist_matrix" + str(i) + ".csv", index=True, header=True)
    
    print("Sample " + str(i) + " created")

Sample 0 created
Sample 1 created
Sample 2 created
Sample 3 created
Sample 4 created
Sample 5 created
Sample 6 created
Sample 7 created
Sample 8 created
Sample 9 created